### APEX WEALTH DATA PIPELINE

In [1]:
%pip install requests

Requirement already satisfied: requests in c:\users\oziom\anaconda3\lib\site-packages (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\oziom\anaconda3\lib\site-packages (from requests) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\oziom\anaconda3\lib\site-packages (from requests) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\oziom\anaconda3\lib\site-packages (from requests) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\oziom\anaconda3\lib\site-packages (from requests) (2025.4.26)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import requests
import pandas as pd
from dotenv import load_dotenv
import os

In [3]:

load_dotenv()
api_key = os.getenv('API_KEY')

In [4]:
API_KEY = os.getenv('API_KEY')

In [5]:
api_key

'0fb28af206c64e9da726186651ad43c2'

In [6]:
symbol = "AAPL"
url =f"https://api.twelvedata.com/time_series?symbol={symbol}&interval=1min&apikey={api_key}&outputsize=20"

In [7]:
#Get response from the API
response = requests.get(url)
response.status_code

200

In [8]:
url =f"https://api.twelvedata.com/time_series?symbol={symbol}&interval=1min&apikey={api_key}&outputsize=20"
params = {
    "symbol": "AAPL",
    "interval": "1day",
    "apikey": API_KEY
}

In [9]:


resp = requests.get(url, params=params)
print("Status code:", resp.status_code)  # Should be 200

data = resp.json()
print("Keys in JSON:", data.keys())      # Should include 'values'

Status code: 200
Keys in JSON: dict_keys(['meta', 'values', 'status'])

In [10]:
#get data in json format
data = response.json()
data

{'meta': {'symbol': 'AAPL',
  'interval': '1min',
  'currency': 'USD',
  'exchange_timezone': 'America/New_York',
  'exchange': 'NASDAQ',
  'mic_code': 'XNGS',
  'type': 'Common Stock'},
 'values': [{'datetime': '2026-02-04 15:37:00',
   'open': '277.67',
   'high': '277.785',
   'low': '277.57',
   'close': '277.7',
   'volume': '9808'},
  {'datetime': '2026-02-04 15:36:00',
   'open': '277.33',
   'high': '277.74',
   'low': '277.33',
   'close': '277.65',
   'volume': '11560'},
  {'datetime': '2026-02-04 15:35:00',
   'open': '277.28',
   'high': '277.51',
   'low': '277',
   'close': '277.34',
   'volume': '12067'},
  {'datetime': '2026-02-04 15:34:00',
   'open': '277.45',
   'high': '277.62',
   'low': '277.22',
   'close': '277.295',
   'volume': '11168'},
  {'datetime': '2026-02-04 15:33:00',
   'open': '277.345',
   'high': '277.555',
   'low': '277.34',
   'close': '277.46',
   'volume': '3324'},
  {'datetime': '2026-02-04 15:32:00',
   'open': '277.06',
   'high': '277.5',
   'low': '277.01',
   'close': '277.325',
   'volume': '4659'},
  {'datetime': '2026-02-04 15:31:00',
   'open': '277.35',
   'high': '277.36',
   'low': '277.03',
   'close': '277.04',
   'volume': '3877'},
  {'datetime': '2026-02-04 15:30:00',
   'open': '277.66',
   'high': '277.73',
   'low': '277.33',
   'close': '277.33',
   'volume': '4369'},
  {'datetime': '2026-02-04 15:29:00',
   'open': '278.02',
   'high': '278.08',
   'low': '277.57',
   'close': '277.61',
   'volume': '8072'},
  {'datetime': '2026-02-04 15:28:00',
   'open': '277.94',
   'high': '277.99',
   'low': '277.725',
   'close': '277.99',
   'volume': '6341'},
  {'datetime': '2026-02-04 15:27:00',
   'open': '277.88',
   'high': '278.03',
   'low': '277.85',
   'close': '277.92',
   'volume': '15479'},
  {'datetime': '2026-02-04 15:26:00',
   'open': '277.56',
   'high': '277.85',
   'low': '277.315',
   'close': '277.84',
   'volume': '13459'},
  {'datetime': '2026-02-04 15:25:00',
   'open': '277.3',
   'high': '277.555',
   'low': '277.215',
   'close': '277.53',
   'volume': '2727'},
  {'datetime': '2026-02-04 15:24:00',
   'open': '277.01',
   'high': '277.26',
   'low': '277',
   'close': '277.26',
   'volume': '3285'},
  {'datetime': '2026-02-04 15:23:00',
   'open': '277.13',
   'high': '277.14',
   'low': '276.83',
   'close': '277',
   'volume': '5713'},
  {'datetime': '2026-02-04 15:22:00',
   'open': '276.61',
   'high': '277.1',
   'low': '276.61',
   'close': '277.1',
   'volume': '13002'},
  {'datetime': '2026-02-04 15:21:00',
   'open': '276.01',
   'high': '276.635',
   'low': '276.01',
   'close': '276.58',
   'volume': '6768'},
  {'datetime': '2026-02-04 15:20:00',
   'open': '276.14',
   'high': '276.16',
   'low': '276.01',
   'close': '276.02',
   'volume': '1790'},
  {'datetime': '2026-02-04 15:19:00',
   'open': '276.07',
   'high': '276.17',
   'low': '276.04',
   'close': '276.11',
   'volume': '12796'},
  {'datetime': '2026-02-04 15:18:00',
   'open': '275.87',
   'high': '276.08',
   'low': '275.835',
   'close': '276.08',
   'volume': '4644'}],
 'status': 'ok'}

In [11]:
df = pd.DataFrame(data["values"])
df.head()

              datetime     open     high     low    close volume
0  2026-02-04 15:37:00   277.67  277.785  277.57    277.7   9808
1  2026-02-04 15:36:00   277.33   277.74  277.33   277.65  11560
2  2026-02-04 15:35:00   277.28   277.51     277   277.34  12067
3  2026-02-04 15:34:00   277.45   277.62  277.22  277.295  11168
4  2026-02-04 15:33:00  277.345  277.555  277.34   277.46   3324

In [12]:
#transform data to dataframe
def transform_data(data):
    #extract values
    time_series = data['values']

    #convert to dataframe
    df = pd.DataFrame(time_series)

    #convert to proper datatypes
    df['datetime'] = pd.to_datetime(df['datetime'])

    df = df.astype({
        'open': 'float',
        'high': 'float',
        'low': 'float',
        'close': 'float',
        'volume': 'int' })
    return df

In [13]:
df = transform_data(data)

In [14]:
df

              datetime     open     high      low    close  volume
0  2026-02-04 15:37:00  277.670  277.785  277.570  277.700    9808
1  2026-02-04 15:36:00  277.330  277.740  277.330  277.650   11560
2  2026-02-04 15:35:00  277.280  277.510  277.000  277.340   12067
3  2026-02-04 15:34:00  277.450  277.620  277.220  277.295   11168
4  2026-02-04 15:33:00  277.345  277.555  277.340  277.460    3324
5  2026-02-04 15:32:00  277.060  277.500  277.010  277.325    4659
6  2026-02-04 15:31:00  277.350  277.360  277.030  277.040    3877
7  2026-02-04 15:30:00  277.660  277.730  277.330  277.330    4369
8  2026-02-04 15:29:00  278.020  278.080  277.570  277.610    8072
9  2026-02-04 15:28:00  277.940  277.990  277.725  277.990    6341
10 2026-02-04 15:27:00  277.880  278.030  277.850  277.920   15479
11 2026-02-04 15:26:00  277.560  277.850  277.315  277.840   13459
12 2026-02-04 15:25:00  277.300  277.555  277.215  277.530    2727
13 2026-02-04 15:24:00  277.010  277.260  277.000  277.260    3285
14 2026-02-04 15:23:00  277.130  277.140  276.830  277.000    5713
15 2026-02-04 15:22:00  276.610  277.100  276.610  277.100   13002
16 2026-02-04 15:21:00  276.010  276.635  276.010  276.580    6768
17 2026-02-04 15:20:00  276.140  276.160  276.010  276.020    1790
18 2026-02-04 15:19:00  276.070  276.170  276.040  276.110   12796
19 2026-02-04 15:18:00  275.870  276.080  275.835  276.080    4644

### Extract data for multiple symbols

In [15]:
symbols = ['AAPL', 'MSFT', 'GOOGL', 'AMZN', 'TSLA']
all_data = []
def fetch_data(symbol, api_key):
    url =f"https://api.twelvedata.com/time_series?symbol={symbol}&interval=1min&apikey={api_key}&outputsize=5"
    response = requests.get(url)
    response.raise_for_status() #raise an error if we get a bad response
    data = response.json()

    if data.get('status') != 'ok':
        raise ValueError(f'Error fetching data for {symbol}: {data.get("message", "Unknown error")}')
    return data

In [46]:
symbols = ['AAPL', 'MSFT', 'GOOGL', 'AMZN', 'TSLA', 'NVDA', 'NFLX', 'META',]


for symbol in symbols:
    data = fetch_data(symbol, api_key)
    df = transform_data(data)
    df['symbol'] = symbol
    all_data.append(df)

all_data

[             datetime    open     high      low    close  volume symbol
 0 2026-02-04 15:39:00  277.57  277.660  277.245  277.380   11410   AAPL
 1 2026-02-04 15:38:00  277.73  277.755  277.440  277.615    7362   AAPL
 2 2026-02-04 15:37:00  277.67  277.785  277.570  277.700    9808   AAPL
 3 2026-02-04 15:36:00  277.33  277.740  277.330  277.650   11560   AAPL
 4 2026-02-04 15:35:00  277.28  277.510  277.000  277.340   12067   AAPL,
              datetime     open     high      low   close  volume symbol
 0 2026-02-04 15:39:00  415.650  415.770  415.470  415.57    2463   MSFT
 1 2026-02-04 15:38:00  415.350  415.560  415.240  415.56    1904   MSFT
 2 2026-02-04 15:37:00  415.395  415.395  415.085  415.32    2877   MSFT
 3 2026-02-04 15:36:00  415.250  415.360  415.200  415.32    2613   MSFT
 4 2026-02-04 15:35:00  415.295  415.320  415.140  415.17    4236   MSFT,
              datetime    open     high      low   close  volume symbol
 0 2026-02-04 15:39:00  333.61  333.630  333.370  333.57    3037  GOOGL
 1 2026-02-04 15:38:00  333.60  333.630  333.450  333.63    3869  GOOGL
 2 2026-02-04 15:37:00  333.53  333.570  333.380  333.57    2513  GOOGL
 3 2026-02-04 15:36:00  333.20  333.535  333.170  333.53    4383  GOOGL
 4 2026-02-04 15:35:00  333.17  333.410  333.115  333.13    4797  GOOGL,
              datetime     open     high      low   close  volume symbol
 0 2026-02-04 15:39:00  234.580  234.590  234.450  234.59    5240   AMZN
 1 2026-02-04 15:38:00  234.720  234.720  234.480  234.57    5431   AMZN
 2 2026-02-04 15:37:00  234.465  234.740  234.465  234.73    4967   AMZN
 3 2026-02-04 15:36:00  234.300  234.510  234.290  234.48    5561   AMZN
 4 2026-02-04 15:35:00  234.410  234.495  234.270  234.30    3414   AMZN,
              datetime     open    high      low    close  volume symbol
 0 2026-02-04 15:39:00  408.835  408.93  408.740  408.790    1237   TSLA
 1 2026-02-04 15:38:00  408.990  409.05  408.730  408.940    2722   TSLA
 2 2026-02-04 15:37:00  408.730  409.15  408.510  409.150    3383   TSLA
 3 2026-02-04 15:36:00  408.670  408.83  408.465  408.775    2273   TSLA
 4 2026-02-04 15:35:00  408.720  408.91  408.590  408.600    1581   TSLA,
              datetime     open     high      low    close  volume symbol
 0 2026-02-04 15:39:00  175.450  175.630  175.315  175.630   19528   NVDA
 1 2026-02-04 15:38:00  175.355  175.475  175.290  175.440   19930   NVDA
 2 2026-02-04 15:37:00  175.255  175.365  175.175  175.335   25888   NVDA
 3 2026-02-04 15:36:00  175.285  175.335  175.115  175.255   23497   NVDA
 4 2026-02-04 15:35:00  175.465  175.465  175.275  175.275   22546   NVDA,
              datetime    open     high      low    close  volume symbol
 0 2026-02-04 15:40:00  277.39  277.450  277.100  277.150   10505   AAPL
 1 2026-02-04 15:39:00  277.57  277.660  277.245  277.380   11410   AAPL
 2 2026-02-04 15:38:00  277.73  277.755  277.440  277.615    7362   AAPL
 3 2026-02-04 15:37:00  277.67  277.785  277.570  277.700    9808   AAPL
 4 2026-02-04 15:36:00  277.33  277.740  277.330  277.650   11560   AAPL,
              datetime     open     high      low   close  volume symbol
 0 2026-02-04 15:40:00  415.590  415.820  415.590  415.80    3448   MSFT
 1 2026-02-04 15:39:00  415.650  415.770  415.470  415.57    2463   MSFT
 2 2026-02-04 15:38:00  415.350  415.560  415.240  415.56    1904   MSFT
 3 2026-02-04 15:37:00  415.395  415.395  415.085  415.32    2877   MSFT
 4 2026-02-04 15:36:00  415.250  415.360  415.200  415.32    2613   MSFT,
              datetime    open     high     low   close  volume symbol
 0 2026-02-04 15:40:00  333.59  333.930  333.57  333.93    3178  GOOGL
 1 2026-02-04 15:39:00  333.61  333.630  333.37  333.57    3037  GOOGL
 2 2026-02-04 15:38:00  333.60  333.630  333.45  333.63    3869  GOOGL
 3 2026-02-04 15:37:00  333.53  333.570  333.38  333.57    2513  GOOGL
 4 2026-02-04 15:36:00  333.20  333.535  333.17  333.53    4383  GOOGL,
              datetime     open    high      low   close  volume symbol
 0 2026-02-04 15:40:00  234.595  234.73  234.580  234.68    5181   AMZN
 1 2026-02-04 15:39:00  234.580  234.59  234.450  234.59    5240   AMZN
 2 2026-02-04 15:38:00  234.720  234.72  234.480  234.57    5431   AMZN
 3 2026-02-04 15:37:00  234.465  234.74  234.465  234.73    4967   AMZN
 4 2026-02-04 15:36:00  234.300  234.51  234.290  234.48    5561   AMZN,
              datetime     open     high      low    close  volume symbol
 0 2026-02-04 15:40:00  408.885  408.885  408.450  408.670    1107   TSLA
 1 2026-02-04 15:39:00  408.835  408.930  408.740  408.790    1237   TSLA
 2 2026-02-04 15:38:00  408.990  409.050  408.730  408.940    2722   TSLA
 3 2026-02-04 15:37:00  408.730  409.150  408.510  409.150    3383   TSLA
 4 2026-02-04 15:36:00  408.670  408.830  408.465  408.775    2273   TSLA,
              datetime     open     high      low    close  volume symbol
 0 2026-02-04 15:40:00  175.620  175.710  175.550  175.625    8532   NVDA
 1 2026-02-04 15:39:00  175.450  175.630  175.315  175.630   19528   NVDA
 2 2026-02-04 15:38:00  175.355  175.475  175.290  175.440   19930   NVDA
 3 2026-02-04 15:37:00  175.255  175.365  175.175  175.335   25888   NVDA
 4 2026-02-04 15:36:00  175.285  175.335  175.115  175.255   23497   NVDA,
              datetime    open    high     low   close  volume symbol
 0 2026-02-04 15:40:00  80.500  80.540  80.450  80.490   12444   NFLX
 1 2026-02-04 15:39:00  80.445  80.490  80.430  80.490   10965   NFLX
 2 2026-02-04 15:38:00  80.445  80.455  80.425  80.445    3194   NFLX
 3 2026-02-04 15:37:00  80.455  80.455  80.390  80.445    4943   NFLX
 4 2026-02-04 15:36:00  80.460  80.485  80.410  80.435    3838   NFLX,
              datetime     open     high      low    close  volume symbol
 0 2026-02-04 15:40:00  672.660  673.450  672.280  673.450    1677   META
 1 2026-02-04 15:39:00  672.265  672.480  672.120  672.480     870   META
 2 2026-02-04 15:38:00  672.190  672.260  672.155  672.240     628   META
 3 2026-02-04 15:37:00  672.070  672.445  672.050  672.445     429   META
 4 2026-02-04 15:36:00  671.880  672.180  671.805  671.920    1004   META]

### APEX WEALTH DATA PIPELINE

In [17]:
%pip install requests

Requirement already satisfied: requests in c:\users\oziom\anaconda3\lib\site-packages (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\oziom\anaconda3\lib\site-packages (from requests) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\oziom\anaconda3\lib\site-packages (from requests) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\oziom\anaconda3\lib\site-packages (from requests) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\oziom\anaconda3\lib\site-packages (from requests) (2025.4.26)
Note: you may need to restart the kernel to use updated packages.

In [18]:
import requests
import pandas as pd
from dotenv import load_dotenv
import os

In [19]:

load_dotenv()
api_key = os.getenv('API_KEY')

In [20]:
API_KEY = os.getenv('API_KEY')

In [21]:
api_key

'0fb28af206c64e9da726186651ad43c2'

In [22]:
symbol = "AAPL"
url =f"https://api.twelvedata.com/time_series?symbol={symbol}&interval=1min&apikey={api_key}&outputsize=20"

In [23]:
#Get response from the API
response = requests.get(url)
response.status_code

200

In [24]:
url =f"https://api.twelvedata.com/time_series?symbol={symbol}&interval=1min&apikey={api_key}&outputsize=20"
params = {
    "symbol": "AAPL",
    "interval": "1day",
    "apikey": API_KEY
}

In [25]:


resp = requests.get(url, params=params)
print("Status code:", resp.status_code)  # Should be 200

data = resp.json()
print("Keys in JSON:", data.keys())      # Should include 'values'

Status code: 200
Keys in JSON: dict_keys(['meta', 'values', 'status'])

In [26]:
#get data in json format
data = response.json()
data

{'meta': {'symbol': 'AAPL',
  'interval': '1min',
  'currency': 'USD',
  'exchange_timezone': 'America/New_York',
  'exchange': 'NASDAQ',
  'mic_code': 'XNGS',
  'type': 'Common Stock'},
 'values': [{'datetime': '2026-02-04 15:38:00',
   'open': '277.73',
   'high': '277.755',
   'low': '277.44',
   'close': '277.615',
   'volume': '7362'},
  {'datetime': '2026-02-04 15:37:00',
   'open': '277.67',
   'high': '277.785',
   'low': '277.57',
   'close': '277.7',
   'volume': '9808'},
  {'datetime': '2026-02-04 15:36:00',
   'open': '277.33',
   'high': '277.74',
   'low': '277.33',
   'close': '277.65',
   'volume': '11560'},
  {'datetime': '2026-02-04 15:35:00',
   'open': '277.28',
   'high': '277.51',
   'low': '277',
   'close': '277.34',
   'volume': '12067'},
  {'datetime': '2026-02-04 15:34:00',
   'open': '277.45',
   'high': '277.62',
   'low': '277.22',
   'close': '277.295',
   'volume': '11168'},
  {'datetime': '2026-02-04 15:33:00',
   'open': '277.345',
   'high': '277.555',
   'low': '277.34',
   'close': '277.46',
   'volume': '3324'},
  {'datetime': '2026-02-04 15:32:00',
   'open': '277.06',
   'high': '277.5',
   'low': '277.01',
   'close': '277.325',
   'volume': '4659'},
  {'datetime': '2026-02-04 15:31:00',
   'open': '277.35',
   'high': '277.36',
   'low': '277.03',
   'close': '277.04',
   'volume': '3877'},
  {'datetime': '2026-02-04 15:30:00',
   'open': '277.66',
   'high': '277.73',
   'low': '277.33',
   'close': '277.33',
   'volume': '4369'},
  {'datetime': '2026-02-04 15:29:00',
   'open': '278.02',
   'high': '278.08',
   'low': '277.57',
   'close': '277.61',
   'volume': '8072'},
  {'datetime': '2026-02-04 15:28:00',
   'open': '277.94',
   'high': '277.99',
   'low': '277.725',
   'close': '277.99',
   'volume': '6341'},
  {'datetime': '2026-02-04 15:27:00',
   'open': '277.88',
   'high': '278.03',
   'low': '277.85',
   'close': '277.92',
   'volume': '15479'},
  {'datetime': '2026-02-04 15:26:00',
   'open': '277.56',
   'high': '277.85',
   'low': '277.315',
   'close': '277.84',
   'volume': '13459'},
  {'datetime': '2026-02-04 15:25:00',
   'open': '277.3',
   'high': '277.555',
   'low': '277.215',
   'close': '277.53',
   'volume': '2727'},
  {'datetime': '2026-02-04 15:24:00',
   'open': '277.01',
   'high': '277.26',
   'low': '277',
   'close': '277.26',
   'volume': '3285'},
  {'datetime': '2026-02-04 15:23:00',
   'open': '277.13',
   'high': '277.14',
   'low': '276.83',
   'close': '277',
   'volume': '5713'},
  {'datetime': '2026-02-04 15:22:00',
   'open': '276.61',
   'high': '277.1',
   'low': '276.61',
   'close': '277.1',
   'volume': '13002'},
  {'datetime': '2026-02-04 15:21:00',
   'open': '276.01',
   'high': '276.635',
   'low': '276.01',
   'close': '276.58',
   'volume': '6768'},
  {'datetime': '2026-02-04 15:20:00',
   'open': '276.14',
   'high': '276.16',
   'low': '276.01',
   'close': '276.02',
   'volume': '1790'},
  {'datetime': '2026-02-04 15:19:00',
   'open': '276.07',
   'high': '276.17',
   'low': '276.04',
   'close': '276.11',
   'volume': '12796'}],
 'status': 'ok'}

In [27]:
df = pd.DataFrame(data["values"])
df.head()

              datetime    open     high     low    close volume
0  2026-02-04 15:38:00  277.73  277.755  277.44  277.615   7362
1  2026-02-04 15:37:00  277.67  277.785  277.57    277.7   9808
2  2026-02-04 15:36:00  277.33   277.74  277.33   277.65  11560
3  2026-02-04 15:35:00  277.28   277.51     277   277.34  12067
4  2026-02-04 15:34:00  277.45   277.62  277.22  277.295  11168

In [28]:
#transform data to dataframe
def transform_data(data):
    #extract values
    time_series = data['values']

    #convert to dataframe
    df = pd.DataFrame(time_series)

    #convert to proper datatypes
    df['datetime'] = pd.to_datetime(df['datetime'])

    df = df.astype({
        'open': 'float',
        'high': 'float',
        'low': 'float',
        'close': 'float',
        'volume': 'int' })
    return df

In [29]:
df = transform_data(data)

In [30]:
df

              datetime     open     high      low    close  volume
0  2026-02-04 15:38:00  277.730  277.755  277.440  277.615    7362
1  2026-02-04 15:37:00  277.670  277.785  277.570  277.700    9808
2  2026-02-04 15:36:00  277.330  277.740  277.330  277.650   11560
3  2026-02-04 15:35:00  277.280  277.510  277.000  277.340   12067
4  2026-02-04 15:34:00  277.450  277.620  277.220  277.295   11168
5  2026-02-04 15:33:00  277.345  277.555  277.340  277.460    3324
6  2026-02-04 15:32:00  277.060  277.500  277.010  277.325    4659
7  2026-02-04 15:31:00  277.350  277.360  277.030  277.040    3877
8  2026-02-04 15:30:00  277.660  277.730  277.330  277.330    4369
9  2026-02-04 15:29:00  278.020  278.080  277.570  277.610    8072
10 2026-02-04 15:28:00  277.940  277.990  277.725  277.990    6341
11 2026-02-04 15:27:00  277.880  278.030  277.850  277.920   15479
12 2026-02-04 15:26:00  277.560  277.850  277.315  277.840   13459
13 2026-02-04 15:25:00  277.300  277.555  277.215  277.530    2727
14 2026-02-04 15:24:00  277.010  277.260  277.000  277.260    3285
15 2026-02-04 15:23:00  277.130  277.140  276.830  277.000    5713
16 2026-02-04 15:22:00  276.610  277.100  276.610  277.100   13002
17 2026-02-04 15:21:00  276.010  276.635  276.010  276.580    6768
18 2026-02-04 15:20:00  276.140  276.160  276.010  276.020    1790
19 2026-02-04 15:19:00  276.070  276.170  276.040  276.110   12796

### Extract data for multiple symbols

In [31]:
symbols = ['AAPL', 'MSFT', 'GOOGL', 'AMZN', 'TSLA', 'NVDA', 'NFLX', 'DIS']
all_data = []
def fetch_data(symbol, api_key):
    url =f"https://api.twelvedata.com/time_series?symbol={symbol}&interval=1min&apikey={api_key}&outputsize=5"
    response = requests.get(url)
    response.raise_for_status() #raise an error if we get a bad response
    data = response.json()

    if data.get('status') != 'ok':
        raise ValueError(f'Error fetching data for {symbol}: {data.get("message", "Unknown error")}')
    return data

In [32]:
#Symbols added to pipeline
# ['AAPL', 'MSFT', 'GOOGL', 'AMZN', 'TSLA', 'NVDA', 'NFLX', 'DIS',]

In [33]:
# PR comment: Verified symbol list updated for diversification
# Symbols added for diversification in PR

In [49]:
symbols = ['AAPL', 'MSFT', 'GOOGL', 'AMZN', 'TSLA', 'NVDA', 'NFLX', 'DIS']

for symbol in symbols:
    data = fetch_data(symbol, api_key)
    df = transform_data(data)
    df['symbol'] = symbol
    all_data.append(df)

all_data

ValueError: Error fetching data for AAPL: You have run out of API credits for the current minute. 11 API credits were used, with the current limit being 8. Wait for the next minute or consider switching to a higher tier plan at https://twelvedata.com/pricing

In [48]:
symbols = ['AAPL', 'MSFT', 'GOOGL', 'AMZN', 'TSLA', 'NVDA', 'NFLX', 'DIS',]

for symbol in symbols:
    data = fetch_data(symbol, api_key)
    df = transform_data(data)
    df['symbol'] = symbol
    all_data.append(df)

all_data

ValueError: Error fetching data for AAPL: You have run out of API credits for the current minute. 10 API credits were used, with the current limit being 8. Wait for the next minute or consider switching to a higher tier plan at https://twelvedata.com/pricing

In [39]:
#concat - joining or stacking all the dataframes together
all_df = pd.concat(all_data, ignore_index=True)

### APEX WEALTH DATA PIPELINE

In [40]:
all_df

              datetime     open     high      low    close  volume symbol
0  2026-02-04 15:39:00  277.570  277.660  277.245  277.380   11410   AAPL
1  2026-02-04 15:38:00  277.730  277.755  277.440  277.615    7362   AAPL
2  2026-02-04 15:37:00  277.670  277.785  277.570  277.700    9808   AAPL
3  2026-02-04 15:36:00  277.330  277.740  277.330  277.650   11560   AAPL
4  2026-02-04 15:35:00  277.280  277.510  277.000  277.340   12067   AAPL
5  2026-02-04 15:39:00  415.650  415.770  415.470  415.570    2463   MSFT
6  2026-02-04 15:38:00  415.350  415.560  415.240  415.560    1904   MSFT
7  2026-02-04 15:37:00  415.395  415.395  415.085  415.320    2877   MSFT
8  2026-02-04 15:36:00  415.250  415.360  415.200  415.320    2613   MSFT
9  2026-02-04 15:35:00  415.295  415.320  415.140  415.170    4236   MSFT
10 2026-02-04 15:39:00  333.610  333.630  333.370  333.570    3037  GOOGL
11 2026-02-04 15:38:00  333.600  333.630  333.450  333.630    3869  GOOGL
12 2026-02-04 15:37:00  333.530  333.570  333.380  333.570    2513  GOOGL
13 2026-02-04 15:36:00  333.200  333.535  333.170  333.530    4383  GOOGL
14 2026-02-04 15:35:00  333.170  333.410  333.115  333.130    4797  GOOGL
15 2026-02-04 15:39:00  234.580  234.590  234.450  234.590    5240   AMZN
16 2026-02-04 15:38:00  234.720  234.720  234.480  234.570    5431   AMZN
17 2026-02-04 15:37:00  234.465  234.740  234.465  234.730    4967   AMZN
18 2026-02-04 15:36:00  234.300  234.510  234.290  234.480    5561   AMZN
19 2026-02-04 15:35:00  234.410  234.495  234.270  234.300    3414   AMZN
20 2026-02-04 15:39:00  408.835  408.930  408.740  408.790    1237   TSLA
21 2026-02-04 15:38:00  408.990  409.050  408.730  408.940    2722   TSLA
22 2026-02-04 15:37:00  408.730  409.150  408.510  409.150    3383   TSLA
23 2026-02-04 15:36:00  408.670  408.830  408.465  408.775    2273   TSLA
24 2026-02-04 15:35:00  408.720  408.910  408.590  408.600    1581   TSLA
25 2026-02-04 15:39:00  175.450  175.630  175.315  175.630   19528   NVDA
26 2026-02-04 15:38:00  175.355  175.475  175.290  175.440   19930   NVDA
27 2026-02-04 15:37:00  175.255  175.365  175.175  175.335   25888   NVDA
28 2026-02-04 15:36:00  175.285  175.335  175.115  175.255   23497   NVDA
29 2026-02-04 15:35:00  175.465  175.465  175.275  175.275   22546   NVDA

#### Loading

In [41]:
load_dotenv()
DB_HOST = os.getenv('DB_HOST')
DB_PORT = os.getenv('DB_PORT')
DB_NAME = os.getenv('DB_NAME')
DB_USER = os.getenv('DB_USER')
DB_PASSWORD = os.getenv('DB_PASSWORD')

In [42]:
import os
from dotenv import load_dotenv

# Load the .env file
load_dotenv(dotenv_path="C:/full/path/to/your/project/.env")  # change this to your actual path

# Get DB_NAME
DB_NAME = os.getenv("DB_NAME")
print("DB_NAME:", DB_NAME)

DB_NAME: apex_db

In [43]:
#create a database connnection url 

from sqlalchemy import create_engine 
import psycopg2


db_url = f'postgresql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}'
engine = create_engine(db_url)

#load dataframe to postgres database
all_df.to_sql('stockPrices_data', engine, if_exists='append', index=False)

print("Data loaded to database successfully")

Data loaded to database successfully

In [44]:
all_df.to_csv('stock_data.csv', index=False)

In [ ]:
#concat - joining or stacking all the dataframes together
all_df = pd.concat(all_data, ignore_index=True)

In [ ]:
all_df

              datetime     open     high      low    close  volume symbol
0  2026-02-02 09:50:00  262.820  263.550  262.820  263.410    4157   AAPL
1  2026-02-02 09:49:00  262.440  262.830  262.275  262.830    6105   AAPL
2  2026-02-02 09:48:00  261.810  262.500  261.760  262.500    2840   AAPL
3  2026-02-02 09:47:00  261.895  261.955  261.520  261.680    4403   AAPL
4  2026-02-02 09:46:00  261.120  262.000  260.955  262.000    6754   AAPL
5  2026-02-02 09:50:00  428.670  429.225  428.600  429.090   13236   MSFT
6  2026-02-02 09:49:00  428.505  428.840  428.270  428.660    7789   MSFT
7  2026-02-02 09:48:00  427.865  428.505  427.690  428.505    4546   MSFT
8  2026-02-02 09:47:00  427.710  428.240  427.600  427.870   11550   MSFT
9  2026-02-02 09:46:00  427.950  428.130  427.700  427.745    4713   MSFT
10 2026-02-02 09:50:00  337.430  338.650  337.330  338.650    8518  GOOGL
11 2026-02-02 09:49:00  337.620  337.740  337.470  337.470    2765  GOOGL
12 2026-02-02 09:48:00  338.190  338.500  337.555  337.555    4004  GOOGL
13 2026-02-02 09:47:00  338.080  338.830  338.010  338.110    9378  GOOGL
14 2026-02-02 09:46:00  337.050  338.010  336.990  338.010    3995  GOOGL
15 2026-02-02 09:50:00  242.170  242.750  242.105  242.745    8597   AMZN
16 2026-02-02 09:49:00  241.720  242.075  241.580  242.075   14864   AMZN
17 2026-02-02 09:48:00  241.245  241.765  241.220  241.745    5219   AMZN
18 2026-02-02 09:47:00  241.205  241.330  241.100  241.250    3747   AMZN
19 2026-02-02 09:46:00  240.875  241.150  240.610  241.150    4220   AMZN

#### Loading

In [ ]:
load_dotenv()
DB_HOST = os.getenv('DB_HOST')
DB_PORT = os.getenv('DB_PORT')
DB_NAME = os.getenv('DB_NAME')
DB_USER = os.getenv('DB_USER')
DB_PASSWORD = os.getenv('DB_PASSWORD')

In [41]:
import os
from dotenv import load_dotenv

# Load the .env file
load_dotenv(dotenv_path="C:/full/path/to/your/project/.env")  # change this to your actual path

# Get DB_NAME
DB_NAME = os.getenv("DB_NAME")
print("DB_NAME:", DB_NAME)

DB_NAME: apex_db

In [45]:
#create a database connnection url 

from sqlalchemy import create_engine 
import psycopg2


db_url = f'postgresql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}'
engine = create_engine(db_url)

#load dataframe to postgres database
all_df.to_sql('stockPrices_data', engine, if_exists='append', index=False)

print("Data loaded to database successfully")

Data loaded to database successfully

In [ ]:
all_df.to_csv('stock_data.csv', index=False)